name: Create build
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Set up nodejs
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18.x'
    - name: Run install
      run: |
        npm install
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'build.7z'
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: build.7z
        tag_name: ${{ github.event.inputs.tags }}
